# -----------------------------------------------------------
# Robust PHP Dockerfile Template
# Generated by WeberQ Infrastructure Scaffolding
# -----------------------------------------------------------

FROM php:8.2-apache

# 1. Install System Dependencies (for GD, Zip, etc.)
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    libicu-dev \
    libonig-dev \
    curl \
    unzip \
    git \
    && rm -rf /var/lib/apt/lists/*

# 2. Configure PHP Extensions
# GD: Configure for JPEG/FreeType support
RUN docker-php-ext-configure gd --with-freetype --with-jpeg

# Install standard extensions
RUN docker-php-ext-install \
    pdo_mysql \
    mysqli \
    gd \
    zip \
    bcmath \
    intl \
    opcache

# 3. Enable Apache mod_rewrite (Crucial for modern frameworks)
RUN a2enmod rewrite

# 4. Set working directory
WORKDIR /var/www/html

# 5. Copy Application Source
COPY . /var/www/html

# 6. Permissions (Ensure Apache can read/write)
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# 7. Use Default Production Configuration
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# (Optional) Increase upload limits - Uncomment if needed
# RUN echo "upload_max_filesize = 64M" > /usr/local/etc/php/conf.d/uploads.ini
# RUN echo "post_max_size = 64M" >> /usr/local/etc/php/conf.d/uploads.ini

EXPOSE 80
