name: Deploy to Google Cloud Instance

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set Variables
      run: |
        echo "INSTANCE_NAME=test" >> $GITHUB_ENV
        echo "ZONE=us-central1-c" >> $GITHUB_ENV
        echo "SSH_USER=weberqbot" >> $GITHUB_ENV
        echo "INSTANCE_IP=34.68.69.253" >> $GITHUB_ENV
        echo "DEPLOY_SCRIPT=Script.sh" >> $GITHUB_ENV
      shell: bash

    - name: Prepare SSH Key
      env:
        SSH_KEY: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
      run: |
        echo "Writing private SSH key..."
        echo "$SSH_KEY" > private_key
        chmod 600 private_key

        echo "Generating public key from private key..."
        ssh-keygen -y -f private_key > private_key.pub || { echo "SSH key generation failed"; exit 1; }

    - name: Setup Known Hosts
      run: |
        echo "Scanning and adding instance to known_hosts..."
        mkdir -p ~/.ssh
        ssh-keyscan -H $INSTANCE_IP >> ~/.ssh/known_hosts || { echo "Failed to add instance to known_hosts"; exit 1; }

    - name: Copy Deploy Script
      run: |
        echo "Copying deploy script ($DEPLOY_SCRIPT) to instance..."
        scp -i private_key "$DEPLOY_SCRIPT" "$SSH_USER@$INSTANCE_IP:~/" || { echo "SCP failed"; exit 1; }

    - name: Execute Deploy Script
      run: |
        echo "Executing deploy script on remote instance..."
        ssh -i private_key "$SSH_USER@$INSTANCE_IP" "bash ~/$DEPLOY_SCRIPT" || { echo "Remote execution failed"; exit 1; }
